name: CI/CD Pipeline

on:
  push:
    branches:
      - Gifts

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploying to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd coordinateApp
            git pull origin backend

            docker compose down

            docker image rm coordinateapp-app

            docker compose up -d
